### ISSUE TITLE
virtual axis requires encoder link to be specified in yaml

### ISSUE THREAD

**Issue by kivel** [paulscherrerinstitute/ecmccfg#172]
even with source set to PLC, the EtherCAT link needs to be provided, which is pointless.

**Comment by kivel** [comment]
no clue, I'm not in Controls anymore and honestly forgot about this.
Feel free to pick the issue.

**Comment by anderssandstrom** [comment]
@shadowguy, you can always use the dummy ethercat entries (ec<master_id>.s<slave_id>.ONE or .ZERO) to override a setting. Anyway, I made a fix making it possible to config an axis without encoder.position link if the encoder.source is set to external/PLC (=1). You can find the updated sources in branch "scotts_issue". Have not been able to test since I work remote. Please test and let me know if it solves your issue (I also installed a version for SLS with the same name as the branch).

**Comment by kivel** [comment]
From reading the template this solution looks good!
handling logic in `jinja` is always a bit "convoluted" isn't it? :) 
@shadowguy please let me know if when you completed some testing with this, so I can inform the guys here as CLS about the improvement.
@anderssandstrom thanks for picking up my crumbs.

**Comment by anderssandstrom** [comment]
@shadowguy, have you managed to test? I will soon release a new version so I would like to know if I can include this.

**Comment by shadowguy** [comment]
Hi @anderssandstrom, I actually don't currently have any ECMC hardware I can test with.  I can ask my officemates when they are back from vacation next week.

**Comment by anderssandstrom** [comment]
Tested and works..
